# Generated by Django 5.1.6 on 2025-03-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('event_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
